In [4]:
from rdflib import Graph, Namespace, RDF, OWL, XSD, Literal
import pandas as pd
g = Graph()

# Load existing graph
g.parse('kg_code/dance_kg_with_data.ttl', format='turtle')

print(f"Loaded {len(g)} triples from existing graph")

Loaded 2281 triples from existing graph

In [5]:
from rdflib.plugins.sparql import prepareQuery

queries = """
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dance: <http://example.org/dance/>
SELECT ?danceStyle ?hardness
WHERE {
 ?record a dance:DanceRecord ;
        dance:hasDanceStyle ?danceStyle ;
        dance:hardnessRatio ?hardness .
 FILTER(xsd:decimal(?hardness) <0.5)
}
#ORDER BY DESC(?hardness)
"""

query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

                                          danceStyle hardness
0  http://example.org/dance/Moonwalk_(Michael_Jac...      0.4
1                  http://example.org/dance/Khaleeji      0.4
2              http://example.org/dance/Rejang_dance      0.4
3                      http://example.org/dance/Haka      0.4
4                    http://example.org/dance/Kagura      0.3
5             http://example.org/dance/Regency_dance      0.4
6          http://example.org/dance/East_Coast_Swing      0.4
7                   http://example.org/dance/Bachata      0.4
8                    http://example.org/dance/Cumbia      0.3
9                     http://example.org/dance/Forró      0.4

In [12]:
from rdflib.plugins.sparql import prepareQuery

queries = """
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dance: <http://example.org/dance/>
PREFIX schema1: <http://schema.org/>

SELECT ?danceName ?instrumentName
WHERE {

 ?record a dance:DanceRecord ;
        dance:hasDanceStyle ?danceStyle ;
        dance:hasInstrument ?instrument .
 ?danceStyle schema1:name ?danceName.
 ?instrument schema1:name ?instrumentName
 FILTER(?instrument = dance:Drums)
}
#ORDER BY DESC(?hardness)
"""

query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

                           danceName instrumentName
0                         Jazz dance          Drums
1   Moonwalk (Michael Jackson style)          Drums
2                        Tap dancing          Drums
3                    Oriental fusion          Drums
4                         Cham dance          Drums
5                  Electric Boogaloo          Drums
6                             Hustle          Drums
7                           Waacking          Drums
8                  Renaissance dance          Drums
9                   East Coast Swing          Drums
10                            Cumbia          Drums
11                       Duranguense          Drums