In [2]:
from rdflib import Graph, Namespace, RDF, OWL, XSD, Literal
import pandas as pd
g = Graph()

# Load existing graph
g.parse('KG_code/dance_kg_with_data.ttl', format='turtle')

print(f"Loaded {len(g)} triples from existing graph")

Loaded 2281 triples from existing graph

In [12]:
from rdflib.plugins.sparql import prepareQuery

queries = """
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dance: <http://example.org/dance/>
SELECT ?danceStyle ?hardness
WHERE {
 ?record a dance:DanceRecord ;
        dance:hasDanceStyle ?danceStyle ;
        dance:hardnessRatio ?hardness .
 FILTER(xsd:decimal(?hardness) <0.5)
}
#ORDER BY DESC(?hardness)
"""

query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

                                          danceStyle hardness
0  http://example.org/dance/Moonwalk_(Michael_Jac...      0.4
1                  http://example.org/dance/Khaleeji      0.4
2              http://example.org/dance/Rejang_dance      0.4
3                      http://example.org/dance/Haka      0.4
4                    http://example.org/dance/Kagura      0.3
5             http://example.org/dance/Regency_dance      0.4
6          http://example.org/dance/East_Coast_Swing      0.4
7                   http://example.org/dance/Bachata      0.4
8                    http://example.org/dance/Cumbia      0.3
9                     http://example.org/dance/Forró      0.4

In [21]:
from rdflib.plugins.sparql import prepareQuery

queries = """
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dance: <http://example.org/dance/>
SELECT ?danceStyle ?instrument
WHERE {
 ?record a dance:DanceRecord ;
        dance:hasDanceStyle ?danceStyle ;
        dance:hasInstrument ?instrument .
 FILTER(?instrument = dance:Drums)
}
#ORDER BY DESC(?hardness)
"""

query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

,danceStyle,instrument
0,http://example.org/dance/Jazz_dance,http://example.org/dance/Drums
1,http://example.org/dance/Moonwalk_(Michael_Jac...,http://example.org/dance/Drums
2,http://example.org/dance/Tap_dancing,http://example.org/dance/Drums
3,http://example.org/dance/Oriental_fusion,http://example.org/dance/Drums
4,http://example.org/dance/Cham_dance,http://example.org/dance/Drums
5,http://example.org/dance/Electric_Boogaloo,http://example.org/dance/Drums
6,http://example.org/dance/Hustle,http://example.org/dance/Drums
7,http://example.org/dance/Waacking,http://example.org/dance/Drums
8,http://example.org/dance/Renaissance_dance,http://example.org/dance/Drums
9,http://example.org/dance/East_Coast_Swing,http://example.org/dance/Drums
10,http://example.org/dance/Cumbia,http://example.org/dance/Drums
11,http://example.org/dance/Duranguense,http://example.org/dance/Drums